services:
  - type: web
    name: mytestweb
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080

databases:
  - name: mytestweb-db
    databaseName: mytestweb
    user: mytestweb_user
