# 개발 환경 전용 설정
spring:
  profiles:
    active: dev
  
  # 개발용 로깅 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 개발용 로깅 설정
logging:
  level:
    com.example.mytestweb: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
